config/routes.rb
Equalpay::Application.routes.draw do
  resources :zips

  root :to => "pages#home"
  resources :SalaryComJobs
  resources :Zips
  
  match '/showmemoney'  => "pages#showmemoney"
  match '/charts' => 'charts#getwagedata'

  
  
end

app/models/blsjob.rb
class Blsjob < ActiveRecord::Base
end

app/models/salary_com_job.rb
class SalaryComJob < ActiveRecord::Base
end

app/models/zip.rb
class Zip < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper:all
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    chartdata = [100]
    render json: chartdata
  end


  def getwagedata
  	data = {:Men => Random.rand(200), :Women => Random.rand(200) }
  	render json: data
  end

end

app/controllers/pages_controller.rb
require 'net/http'
require 'rexml/document'
require 'digest/sha1'

class PagesController < ApplicationController
	include ChartsHelper
  def home
    # @title = "home"
  end
  
  def showmemoney

	  if not params[:jobcode].nil?
	  	
	  	salarycomjob = SalaryComJob.where(:code => params[:jobcode]).limit(1)

	  	if salarycomjob.count > 0

	  		blsjob = Blsjob.where(:bls_job_code => salarycomjob.first.bls_job_code).limit(1)

		  	bls_nf   = blsjob.first.workers_women     # number of females
			bls_nm = blsjob.first.workers_men     # number of male workers
			bls_wf  = blsjob.first.earnings_women   # wage of women (median salary)
			bls_wm = blsjob.first.earnings_men # wage of men (median salary)

			# compute percent female
			pf = bls_nf.to_f / (bls_nm+bls_nf).to_f

			# compute the gap
			g = bls_wf.to_f / bls_wm.to_f
			
			paychktype = params[:paychk_radio].to_f
			# From Salary.com we have the median wage
			sc_w = 1100   # getsalarywebservicedata(salarycomjob.first.code)

			# we want to estimate the wage for females and wage for male
			
			wm = (sc_w.to_f / (pf * g + 1 - pf).to_f)
			wf   = (g.to_f * wm.to_f)
			
			wm = (wm * paychktype).round(2)
			wf = (wf * paychktype).round(2)

			years = [0,5,10,15,20,25,30]
			inflation = 0.03
			

			@highchartdata = {:Men => wm, :Women => wf }
	  		@wagegaptrend = {:Men => years.map {|y| (wm*(1 + inflation)**y).round(2)}, :Women => years.map {|y| ( wf*(1 + inflation)**y).round(2)} }
	  	end
	  	

	  end
  	
  end

  private

  def getsalarywebservicedata(jobcode)
  	# Compute UTC Time

  	debugger
       t = Time.now.utc
       
       mon = t.month
       dd = t.day
       yyyy = t.year
       hh = t.hour
       min = t.min
       sec = t.sec

       # Build a time stamp
        utctimeStamp = mon.to_s+'%2F'+dd.to_s+'%2F'+yyyy.to_s+'+'+hh.to_s+'%3A'+min.to_s + '%3A'+ sec.to_s + t.strftime("%p")
       # they may want +PM or +AM at the end of the timestamp?
       

       # Use security key provided
       securityKey = 'SalaryHR'

       # Use an exmple job code
       jobCode = 'CM02000003'    #Job Code of senior technical writer

       # use a Pittsburgh zip code
       zip = '15216'     #complete with 5 digit postal code

       # Use provided partner code
       partnerCode = 'EQUIPAY4094055567106'   #API-Key or partner code
       

       # build a hash code

       # create string to be hashed
       stringToBeHashed = securityKey+'-'+partnerCode+'-'+utctimeStamp

       stringToBeHashed.strip!

       
       #convert to UTF-8

       stringToBeHashed.force_encoding("UTF-8")
       stringToBeHashed = stringToBeHashed.encode("UTF-8")

       #compute hash using SHA1
       hashCode = Digest::SHA1.new << stringToBeHashed

       # Build URL
       mainURL =
       'http://api.salary.com/salarywizard/layoutscripts/Compdata.asp?'
       jobCodeURL = 'jobcode='+jobCode
       zipCodeURL = '&zip=' + zip
       partnerCodeURL = '&partnercode=' + partnerCode
       utctimestampurl = '&utctime=' + utctimeStamp
       hashKeyURL = '&hashkey=' + hashCode.to_s.upcase
       url = mainURL+jobCodeURL+ zipCodeURL+ partnerCodeURL+ utctimestampurl+hashKeyURL
       

       # get the XML data as a string
       xml_data = Net::HTTP.get_response(URI.parse(url)).body
       mediansalary = xml_data['BenefitBaseSalary50th_M']
  end
  
end

app/controllers/salary_com_jobs_controller.rb
class SalaryComJobsController < ApplicationController
  def index
    @salarycomjobs = SalaryComJob.order(:title).where("title like ?", "%#{params[:term]}%").limit(15).uniq()
    render json: @salarycomjobs.map{|job| {label: job.title, value: job.code}}
  end
end

app/controllers/zips_controller.rb
class ZipsController < ApplicationController
  # GET /zips
  # GET /zips.json
  def index
    @zips = Zip.order(:locationtext).where("zipcode like ? OR locationtext like ?", "#{params[:term]}%", "%#{params[:term]}%").limit(15)
    render json: @zips.map{|z| {label: z.locationtext + ' - ' + z.zipcode, value: z.zipcode}}

    
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper

	
end

app/helpers/charts_helper.rb
module ChartsHelper
  def chart_wagegap

    data = {:Men => Random.rand(200), :Women => Random.rand(200) }
  end

  private 
  
  def getwagegap
  	# This is a Ruby program that shows the computations required by the
	# Pay Gap Application.
	# This program was based on conversations with Professor Linda Babcock.
	# At the bottom of this program is the email message from Professor 
	# Babcock.

	# Some variable values are got from the US Bureau of Labor Statistics 
	# (BLS)
	# and others are retrieved from Salary.com.
	# In this program, all variables got from BLS are prefixed with bls. Those
	# retrieved from salary.com are prefixed with sc. Those values that are 
	# computed
	# have no prefix.
	# The constant values in this code are simply for testing.

	# From BLS we need the following values:
	bls_nf   =  100     # number of females
	bls_nm = 120     # number of male workers
	bls_wf  = 1000   # wage of women (median salary)
	bls_wm = 1200 # wage of men (median salary)

	# compute percent female
	pf = bls_nf.to_f / (bls_nm+bls_nf).to_f

	# compute the gap
	g = bls_wf.to_f / bls_wm.to_f
	# From Salary.com we have the median wage
	sc_w = 1100

	# we want to estimate the wage for females and wage for male
	wm = sc_w.to_f / (pf * g + 1 - pf).to_f
	wf   = g.to_f * wm.to_f
	  	
	end

end

app/helpers/salary_com_jobs_helper.rb
module SalaryComJobsHelper
	
end

app/helpers/zips_helper.rb
module ZipsHelper
end

app/views/layouts/_footer.html.erb
<div id="footer" class="span-23 last">
	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	
</div>

app/views/layouts/_header.html.erb
<div id="header" class="span-24 last">
	<h1>
<%=link_to (image_tag "logo.png", :title => "Logo") , root_path %>
</h1>

</div>
<div id="mainmenu" class="span-24 last">
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Show me the money", showmemoney_path %></li>
		<li><%= link_to "Ask for it", root_path %></li>
		<li><%= link_to "Find out more", root_path %></li>
      
	</ul>
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen, projection' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen'  %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Equal Pay</title>
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
	
	<div  class="container">
		<div id="topspacer"></div>
		<div id="page_container" class="span-24 last">
			<%= render 'layouts/header' %>
			<div id="content">
				<div id="mainsection" class="span-16 append-1">
				<%= yield %>	
				</div>
				<div id="sidebar" class="span-6 last">
					<div id="sidebaritem">
						<div id="sidebaritemheader">
							Did you know?
							
						</div>
						<div id="sidebaritemcontent">
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							
						</div>
						
					</div>
				

				</div>



			</div>
			
			<%= render 'layouts/footer'%>
		</div>
		
		</div>
		<div id="bottomspacer"></div>



</body>
</html>

app/views/pages/askforit.html.erb
<div id="left" class="span-5">
	
</div>
<div id="videos" class="span-10">
	<%= video_tag %>
</div>

app/views/pages/home.html.erb
<div>
	

<h2>Welcome</h2>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>

app/views/pages/showmemoney.html.erb
<div id="verticalnavbar" class="span-3">
<ul>
	<li><a id="occup_link" href="#">Occupation</a> </li>
	<li><a id="loc_link" href="#">Location</a> </li>
	<li><a id="gend_link" href="#">Gender</a> </li>
	<li><a id="paychk_link" href="#">Paycheck</a> </li>
</ul>
	
</div>

<div id="userform" class="span-10">
	<div id="occupation">

		
		


<%= form_tag("/showmemoney", :method => "get") do %>
  		<%= label_tag(:q, "Start typing your job title") %> <br/>
  		<%= text_field :salarycomjob, :jobtitle, :size => 50,  :class => 'searchbox'  %>
  		<%= hidden_field_tag :jobcode %>
          		
	

	
		
		<a id="nextlink1" href="#" class="button orange">Next</a>
		
	</div>
	
	
	<div id="location">
		<label for="zipcode">Start typing city or zipcode</label> <br/>
		<input type="text" name="" value="" id="zipcodefield" size="50"class="searchbox">
		
		<a id="nextlink2" href="#" class="button orange">Next</a>
	</div>
	
	
	<div id="gender">
		<h5>Select gender</h5>

		
		<input type="radio" name="gender_radio" value="Male"> Male<br/>
		<input type="radio" name="gender_radio" value="Female">Female
		<a id="nextlink3" href="#" class="button orange">Next</a>

	</div>
	
	<div id="paycheck">
		<h5>Select Paycheck type</h5>
		<input type="radio" name="paychk_radio" value="52.177"> Yearly Salary<br/>
		<input type="radio" name="paychk_radio" value="4.348"> Monthly Salary <br/>
		<input type="radio" name="paychk_radio" value="0.025"> Hourly Wages <br/>
	    <%= submit_tag("Show me the money", :id => "showmemoney", :class => "button orange") %>
		<% end %>

	</div>
	
	<%= content_tag "div", id:"mydatadiv", data: {chartdata: @highchartdata, wagegaptrend: @wagegaptrend }   do %>
	<% end %>


	

	
</div>



<div id="chartscontainer" class="span-16 last">
		
	</div>
	
	<div id="chartscontainer2" class="span-16 last">
		
	</div>
<div class="span-24 last">
<%= debug params %>
<%= debug @highchartdata %>
</div>

app/views/zips/_form.html.erb
<%= form_for(@zip) do |f| %>
  <% if @zip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zip.errors.count, "error") %> prohibited this zip from being saved:</h2>

      <ul>
      <% @zip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :locationtext %><br />
    <%= f.text_field :locationtext %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zips/edit.html.erb
<h1>Editing zip</h1>

<%= render 'form' %>

<%= link_to 'Show', @zip %> |
<%= link_to 'Back', zips_path %>

app/views/zips/index.html.erb
<h1>Listing zips</h1>

<table>
  <tr>
    <th>Zipcode</th>
    <th>City</th>
    <th>State</th>
    <th>Locationtext</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zips.each do |zip| %>
  <tr>
    <td><%= zip.zipcode %></td>
    <td><%= zip.city %></td>
    <td><%= zip.state %></td>
    <td><%= zip.locationtext %></td>
    <td><%= link_to 'Show', zip %></td>
    <td><%= link_to 'Edit', edit_zip_path(zip) %></td>
    <td><%= link_to 'Destroy', zip, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zip', new_zip_path %>

app/views/zips/new.html.erb
<h1>New zip</h1>

<%= render 'form' %>

<%= link_to 'Back', zips_path %>

app/views/zips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Zipcode:</b>
  <%= @zip.zipcode %>
</p>

<p>
  <b>City:</b>
  <%= @zip.city %>
</p>

<p>
  <b>State:</b>
  <%= @zip.state %>
</p>

<p>
  <b>Locationtext:</b>
  <%= @zip.locationtext %>
</p>


<%= link_to 'Edit', edit_zip_path(@zip) %> |
<%= link_to 'Back', zips_path %>